name: ci-pre-commit

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    uses: jay-withers/workflows/.github/workflows/pre-commit.yml@0a18e55d654e22fa54c4085547e4389896be6b7f # v1.4.0
    with:
      terraform: true
